services:
  # --- 1. APPLICATION (Ton Code) ---
  app:
    image: vehicle-service:latest
    container_name: vehicle-service-app
    restart: always
    ports:
      - "8080:8080" # Seul port exposé (ou via Nginx)
    depends_on:
      - postgres
      - redis
      - kafka
      - stock-mock
    environment:
      # Active le profil prod (voir application.prod.yml)
      - SPRING_PROFILES_ACTIVE=staging
      
      # Remplacer 'localhost' par les noms des services définis ci-dessous
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=reactivedb
      - DB_USERNAME=user
      - DB_PASSWORD=password
      
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      
      # Kafka interne
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      
      # Services Externes
      - EXTERNAL_HOST=stock-mock

  # --- 2. BASE DE DONNÉES ---
  postgres:
    image: postgres:15-alpine
    container_name: prod-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reactivedb
    # Pas de "ports:" ici par sécurité (accès interne uniquement)
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

  # --- 3. CACHE ---
  redis:
    image: redis:7-alpine
    container_name: prod-redis
    restart: always
    # Pas de "ports:" ici par sécurité

  # --- 4. MESSAGING (Kafka & Zookeeper) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: prod-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: prod-kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # ⚠️ TRES IMPORTANT POUR DOCKER :
      # On dit à Kafka : "Si quelqu'un te cherche, dis-lui que tu t'appelles 'kafka' sur le port 9092"
      # C'est ce qui permet à ton conteneur 'app' de trouver 'kafka'.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # --- 5. MOCKS (Optionnel en Prod, mais utile si tu n'as pas encore le vrai service) ---
  stock-mock:
    image: wiremock/wiremock:2.35.0
    container_name: prod-stock-mock
    restart: always
    command:
      - "--verbose"
      - "--global-response-templating"
    volumes:
      - ./wiremock:/home/wiremock

volumes:
  postgres_prod_data: